name: CI/CD Deploy .NET App with Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 👉 Kết nối VPN trước khi SSH
    - name: Install OpenVPN & Connect
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn
        echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
        sudo openvpn --config vpn-config.ovpn --daemon

    # Đợi VPN kết nối (5 giây)
    - name: Wait for VPN Connection
      run: sleep 5

    - name: Ping Server
      run: ping -c 4 ${{ secrets.SERVER_IP }}

    # Cài đặt SSH Key
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    # 🚀 Deploy lên server và chạy docker-compose
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # 📂 Bước 1: Vào thư mục chứa source code
          cd /home/hoangpham23/BE-VaccineChildren

          # 🔄 Bước 2: Pull source code mới nhất
          git pull origin master

          # 🛑 Bước 3: Dừng container cũ
          docker-compose down

          # 🚀 Bước 4: Build lại container mới và chạy
          docker-compose up --build -d
        EOF
